version: "3.9"

services:
  spimex-parser:
    build: .
    container_name: spimex-parser
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+psycopg2://postgres:password@db:5432/spimex_trading_results
    command: python main.py

  db:
    image: postgres:15
    container_name: spimex-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spimex_trading_results
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
