"""initial2

Revision ID: a5caf78ed0c8
Revises: 5f1c89d5463e
Create Date: 2025-08-07 06:39:36.628579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5caf78ed0c8'
down_revision: Union[str, Sequence[str], None] = '5f1c89d5463e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_result',
    sa.Column('exchange_product_id', sa.String(), nullable=False),
    sa.Column('exchange_product_name', sa.String(), nullable=False),
    sa.Column('oil_id', sa.String(length=4), nullable=False),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=False),
    sa.Column('delivery_basis_name', sa.String(), nullable=False),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('async_spimex_trading_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_spimex_trading_results',
    sa.Column('exchange_product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exchange_product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('oil_id', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('delivery_basis_id', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('delivery_basis_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('delivery_type_id', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('async_spimex_trading_results_pkey'))
    )
    op.drop_table('spimex_trading_result')
    # ### end Alembic commands ###
